export interface DigestData {
  overallStatus: string;
  weekNumber: number;
  summaryLine: string;
  containers: Array<{ name: string; status: string; uptimePercent: number; restarts: number }>;
  endpoints?: Array<{ name: string; uptimePercent: number | null; avgResponseMs: number | null }>;
  trends: Array<{ name: string; cpuChange: number | null; ramChange: number | null }>;
  disk: Array<{ mount_point: string; total_gb: number; used_gb: number; used_percent: number }>;
  diskWarnings: Array<{ mount_point: string; used_percent: number }>;
  updatesAvailable: Array<{ container_name: string; image: string }>;
  overallUptime: number;
  totalRestarts: number;
  restartedContainers: string[];
  generatedAt: string;
}

const STATUS_ICONS: Record<string, string> = { green: '\u{1F7E2}', yellow: '\u{1F7E1}', red: '\u{1F534}' };
const TREND_ARROW = (change: number): string => change > 0 ? '\u2191' : change < 0 ? '\u2193' : '\u2192';

function renderHtml(digest: DigestData): string {
  const icon = STATUS_ICONS[digest.overallStatus];

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f5f5f5; margin: 0; padding: 20px; }
  .container { max-width: 600px; margin: 0 auto; background: #fff; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
  .header { padding: 24px; background: ${digest.overallStatus === 'green' ? '#059669' : digest.overallStatus === 'yellow' ? '#d97706' : '#dc2626'}; color: #fff; }
  .header h1 { margin: 0; font-size: 20px; font-weight: 600; }
  .header .subtitle { opacity: 0.9; margin-top: 4px; font-size: 14px; }
  .section { padding: 20px 24px; border-bottom: 1px solid #e5e7eb; }
  .section h2 { margin: 0 0 12px 0; font-size: 15px; font-weight: 600; color: #374151; text-transform: uppercase; letter-spacing: 0.5px; }
  .metric { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #f3f4f6; }
  .metric:last-child { border-bottom: none; }
  .metric .label { color: #6b7280; }
  .metric .value { font-weight: 600; color: #111827; }
  .status-dot { display: inline-block; width: 8px; height: 8px; border-radius: 50%; margin-right: 6px; }
  .green { background: #059669; }
  .yellow { background: #d97706; }
  .red { background: #dc2626; }
  .trend { font-size: 13px; color: #6b7280; }
  .trend.flagged { color: #d97706; font-weight: 500; }
  .footer { padding: 16px 24px; text-align: center; font-size: 12px; color: #9ca3af; }
  .summary { font-size: 16px; padding: 16px 24px; background: #f9fafb; color: #374151; }
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>${icon} Insightd \u2014 Week ${digest.weekNumber}</h1>
    <div class="subtitle">${digest.summaryLine}</div>
  </div>

  <div class="summary">
    ${renderSummaryBlock(digest)}
  </div>

  ${digest.containers.length > 0 ? renderContainersSection(digest) : ''}
  ${digest.endpoints && digest.endpoints.length > 0 ? renderEndpointsSection(digest) : ''}
  ${digest.trends.length > 0 ? renderTrendsSection(digest) : ''}
  ${digest.disk.length > 0 ? renderDiskSection(digest) : ''}
  ${digest.updatesAvailable.length > 0 ? renderUpdatesSection(digest) : ''}

  <div class="footer">
    Generated by Insightd at ${new Date(digest.generatedAt).toLocaleString()}
  </div>
</div>
</body>
</html>`;
}

function renderSummaryBlock(d: DigestData): string {
  const lines: string[] = [];
  lines.push(`<strong>Uptime:</strong> ${d.overallUptime}%`);
  if (d.totalRestarts > 0) {
    lines.push(`<strong>Restarts:</strong> ${d.totalRestarts} (${d.restartedContainers.join(', ')})`);
  } else {
    lines.push(`<strong>Restarts:</strong> 0`);
  }
  lines.push(`<strong>Updates:</strong> ${d.updatesAvailable.length} container${d.updatesAvailable.length !== 1 ? 's' : ''} have new versions`);
  if (d.diskWarnings.length > 0) {
    lines.push(`<strong>Disk:</strong> \u26A0\uFE0F ${d.diskWarnings.map(w => `${w.mount_point} at ${w.used_percent}%`).join(', ')}`);
  }
  return lines.join('<br>');
}

function renderContainersSection(d: DigestData): string {
  const rows = d.containers.map(c => `
    <div class="metric">
      <span class="label"><span class="status-dot ${c.status}"></span>${c.name}</span>
      <span class="value">${c.uptimePercent}% uptime${c.restarts > 0 ? ` \u00B7 ${c.restarts} restart${c.restarts > 1 ? 's' : ''}` : ''}</span>
    </div>`).join('');

  return `<div class="section"><h2>Containers</h2>${rows}</div>`;
}

function renderEndpointsSection(d: DigestData): string {
  const rows = (d.endpoints || []).map(ep => {
    const status = ep.uptimePercent == null ? 'yellow' : ep.uptimePercent >= 99 ? 'green' : ep.uptimePercent >= 90 ? 'yellow' : 'red';
    const uptime = ep.uptimePercent != null ? `${ep.uptimePercent}%` : 'No data';
    const avgMs = ep.avgResponseMs != null ? `${ep.avgResponseMs}ms` : '-';
    return `
    <div class="metric">
      <span class="label"><span class="status-dot ${status}"></span>${ep.name}</span>
      <span class="value">${uptime} uptime \u00B7 ${avgMs} avg</span>
    </div>`;
  }).join('');

  return `<div class="section"><h2>Endpoint Uptime</h2>${rows}</div>`;
}

function renderTrendsSection(d: DigestData): string {
  const rows = d.trends.map(t => {
    const parts: string[] = [];
    if (t.ramChange !== null) parts.push(`RAM ${TREND_ARROW(t.ramChange)} ${Math.abs(t.ramChange)}%`);
    if (t.cpuChange !== null) parts.push(`CPU ${TREND_ARROW(t.cpuChange)} ${Math.abs(t.cpuChange)}%`);
    return `
    <div class="metric">
      <span class="label">${t.name}</span>
      <span class="value trend flagged">${parts.join(' \u00B7 ')}</span>
    </div>`;
  }).join('');

  return `<div class="section"><h2>Resource Trends</h2>${rows}</div>`;
}

function renderDiskSection(d: DigestData): string {
  const rows = d.disk.map(disk => {
    const warn = disk.used_percent >= 85 ? ' \u26A0\uFE0F' : '';
    return `
    <div class="metric">
      <span class="label">${disk.mount_point}</span>
      <span class="value">${disk.used_gb}/${disk.total_gb} GB (${disk.used_percent}%)${warn}</span>
    </div>`;
  }).join('');

  return `<div class="section"><h2>Disk Usage</h2>${rows}</div>`;
}

function renderUpdatesSection(d: DigestData): string {
  const rows = d.updatesAvailable.map(u => `
    <div class="metric">
      <span class="label">${u.container_name}</span>
      <span class="value">${u.image}</span>
    </div>`).join('');

  return `<div class="section"><h2>Updates Available</h2>${rows}</div>`;
}

function renderPlainText(digest: DigestData): string {
  const icon = STATUS_ICONS[digest.overallStatus];
  const lines: string[] = [
    `${icon} Insightd \u2014 Week ${digest.weekNumber}`,
    '',
    `Uptime:       ${digest.overallUptime}%`,
    `Restarts:     ${digest.totalRestarts}${digest.restartedContainers.length > 0 ? `  (${digest.restartedContainers.join(', ')})` : ''}`,
    `Updates:      ${digest.updatesAvailable.length} containers have new versions available`,
  ];

  if (digest.trends.length > 0) {
    lines.push(`Resources:    ${digest.trends.map(t => {
      const parts: string[] = [];
      if (t.ramChange) parts.push(`${Math.abs(t.ramChange)}% ${t.ramChange > 0 ? 'more' : 'less'} RAM`);
      if (t.cpuChange) parts.push(`${Math.abs(t.cpuChange)}% ${t.cpuChange > 0 ? 'more' : 'less'} CPU`);
      return `${t.name} using ${parts.join(', ')}`;
    }).join('; ')}`);
  }

  if (digest.endpoints && digest.endpoints.length > 0) {
    lines.push('');
    lines.push('Endpoints:');
    for (const ep of digest.endpoints) {
      const uptime = ep.uptimePercent != null ? `${ep.uptimePercent}%` : 'No data';
      const avgMs = ep.avgResponseMs != null ? `${ep.avgResponseMs}ms avg` : '';
      lines.push(`  ${ep.name}: ${uptime} uptime${avgMs ? ` \u00B7 ${avgMs}` : ''}`);
    }
  }

  if (digest.diskWarnings.length > 0) {
    lines.push(`Disk:         \u26A0\uFE0F ${digest.diskWarnings.map(w => `${w.mount_point} at ${w.used_percent}%`).join(', ')}`);
  }

  lines.push('', digest.summaryLine);
  return lines.join('\n');
}

module.exports = { renderHtml, renderPlainText };
